name: audioplayers
description: A Flutter plugin to play multiple audio files simultaneously
version: 1.0.0
homepage: https://github.com/luanpotter/audioplayers

flutter:
  plugin:
    platforms:
      android:
        package: xyz.luan.audioplayers
        pluginClass: AudioplayersPlugin
      ios:
        pluginClass: AudioplayersPlugin

dependencies:
  uuid: ^4.3.3
  path_provider: ^2.1.1
  http: ^0.13.1
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.10.0"
